name: Generate quest list
on:
  [push, pull_request]

jobs:
  generate-quest-list:
    name: Generate quest list
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-java@v1
      #  with:
      #    java-version: 11
      #- run: sudo snap install kotlin --channel=1.4/stable --classic
      - run: wget https://github.com/JetBrains/kotlin/releases/download/v1.4.31/kotlin-compiler-1.4.31.zip
      - run: unzip kotlin-compiler-1.4.31.zip
      - run: rm kotlin-compiler-1.4.31.zip
      - run: sudo mkdir -p /foo/bar/
      - run: sudo mv kotlinc /foo/bar/
      #- run: sudo apt-get install tree
      #- run: sudo tree .
      #- run: kotlinc -script -Xplugin=/snap/kotlin/current/lib/kotlinx-serialization-compiler-plugin.jar .github/generate-quest-list.main.kts
      - run: /foo/bar/kotlinc/bin/kotlinc -script -Xplugin=/foo/bar/kotlinc/lib/kotlinx-serialization-compiler-plugin.jar .github/generate-quest-list.main.kts
      - run: touch .github/generate-quest-list.main.kts
      - run: /foo/bar/kotlinc/bin/kotlinc -script -Xplugin=/foo/bar/kotlinc/lib/kotlinx-serialization-compiler-plugin.jar .github/generate-quest-list.main.kts
      - run: sed -i -e s/values/values-en-rGB/g .github/generate-quest-list.main.kts
      - run: /foo/bar/kotlinc/bin/kotlinc -script -Xplugin=/foo/bar/kotlinc/lib/kotlinx-serialization-compiler-plugin.jar .github/generate-quest-list.main.kts
      - run: " git checkout -- .github/generate-quest-list.main.kts"
      - run: /foo/bar/kotlinc/bin/kotlinc -script -Xplugin=/foo/bar/kotlinc/lib/kotlinx-serialization-compiler-plugin.jar .github/generate-quest-list.main.kts
      - uses: actions/upload-artifact@v2
        with:
          name: quest-list.csv
          path: ./quest-list.csv
